# Generated by Django 2.2.16 on 2021-11-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211109_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('MODERATOR', 'moderator'), ('USER', 'user')], default='user', max_length=10, verbose_name='User role'),
        ),
    ]
