# Generated by Django 2.2.16 on 2021-11-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20211111_1104'),
        ('reviews', '0004_auto_20211111_0719'),
    ]

    operations = [
    ]
